export const SELECCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE';
export const SELECCIONA_PRODUCTO = 'SELECCIONA_PRODUCTO';
export const CANTIDAD_PRODUCTOS = 'CANTIDAD_PRODUCTOS';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';